# Site settings
title: Small White Cube
email: cphillips@smallwhitecube.com
description: > 
  The personal website of Caleb Phillips.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smallwhitecube.com.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
